# fly.toml file generated for ismael-datingapp-curso on 2023-04-11T14:38:13+02:00

app = "ismael-datingapp-curso"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "mad"
processes = []

[build]
  image = "rissquez/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dcwzvr8hx"
  CloudinarySettings__ApiKey="498343996957917"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
